'use client';
import { useEffect, useState } from 'react';
import { Warehouse, Plus, ArrowRightLeft, Send, PackageCheck, Ban } from 'lucide-react';
import { useAuth } from '@/context/AuthContext';

type Bodega={idbodega:number;nombre:string;descripcion:string;principal:number;usuarios:number;unidades:number};
type Producto={idproducto:number;nombre_producto:string;codigo_barra:string;stock:number};
type Item={idproducto:number;nombre_producto:string;cantidad:number;stock:number};
type Transferencia={idtransferencia:number;numero:string;bodega_origen:string;bodega_destino:string;estado:string;productos:number;unidades:number;creado_en:string;idbodega_origen:number;idbodega_destino:number};

export default function WarehousesPage(){
 const {user}=useAuth(); const admin=Number(user?.tipo_usuario)===1;
 const [bodegas,setBodegas]=useState<Bodega[]>([]),[transfers,setTransfers]=useState<Transferencia[]>([]);
 const [origin,setOrigin]=useState(0),[destination,setDestination]=useState(0),[query,setQuery]=useState('');
 const [products,setProducts]=useState<Producto[]>([]),[items,setItems]=useState<Item[]>([]);
 const [name,setName]=useState(''),[description,setDescription]=useState('');
 const load=async()=>{const [b,t]=await Promise.all([fetch('/api/warehouses').then(r=>r.json()),fetch('/api/transfers').then(r=>r.json())]);setBodegas(Array.isArray(b)?b:[]);setTransfers(Array.isArray(t)?t:[]);if(!origin&&user?.idbodega)setOrigin(Number(user.idbodega));};
 useEffect(()=>{load()},[user]);
 useEffect(()=>{if(!origin){setProducts([]);return}fetch(`/api/warehouses/inventory?warehouseId=${origin}&q=${encodeURIComponent(query)}`).then(r=>r.json()).then(d=>setProducts(Array.isArray(d)?d:[]));},[origin,query]);
 const createWarehouse=async(e:React.FormEvent)=>{e.preventDefault();const r=await fetch('/api/warehouses',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nombre:name,descripcion:description})});const d=await r.json();if(!r.ok)return alert(d.error);setName('');setDescription('');load();};
 const add=(p:Producto)=>setItems(v=>v.some(x=>x.idproducto===p.idproducto)?v:[...v,{idproducto:p.idproducto,nombre_producto:p.nombre_producto,cantidad:1,stock:Number(p.stock)}]);
 const createTransfer=async()=>{const r=await fetch('/api/transfers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idbodega_origen:origin,idbodega_destino:destination,items})});const d=await r.json();if(!r.ok)return alert(d.error);setItems([]);setDestination(0);load();alert('Transferencia creada como pendiente');};
 const action=async(id:number,action:string)=>{const r=await fetch(`/api/transfers/${id}/status`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});const d=await r.json();if(!r.ok)return alert(d.error);load();};
 return <div className="p-8 space-y-8">
  <div><h1 className="text-3xl font-black text-slate-800 flex gap-3"><Warehouse className="text-indigo-600"/>Bodegas e inventario</h1><p className="text-slate-500">Existencias, asignaciones y transferencias con confirmación de recepción.</p></div>
  <div className="grid md:grid-cols-3 gap-4">{bodegas.map(b=><div key={b.idbodega} className="bg-white border rounded-2xl p-5 shadow-sm"><div className="flex justify-between"><h2 className="font-black text-slate-800">{b.nombre}</h2>{b.principal===1&&<span className="text-xs bg-indigo-100 text-indigo-700 px-2 py-1 rounded-full">Principal</span>}</div><p className="text-sm text-slate-500 mt-2">{b.descripcion}</p><div className="flex gap-5 mt-4 text-sm"><span><b>{Number(b.unidades)}</b> unidades</span><span><b>{b.usuarios}</b> usuarios</span></div></div>)}</div>
  {admin&&<form onSubmit={createWarehouse} className="bg-white border rounded-2xl p-5 flex flex-wrap gap-3 items-end"><div><label className="text-xs font-bold text-slate-500">NOMBRE</label><input required value={name} onChange={e=>setName(e.target.value)} className="block border rounded-xl p-3"/></div><div className="flex-1 min-w-64"><label className="text-xs font-bold text-slate-500">DESCRIPCIÓN</label><input value={description} onChange={e=>setDescription(e.target.value)} className="block border rounded-xl p-3 w-full"/></div><button className="bg-indigo-600 text-white rounded-xl px-5 py-3 font-bold flex gap-2"><Plus/>Crear bodega</button></form>}
  <section className="bg-white border rounded-3xl p-6 space-y-5"><h2 className="text-xl font-black flex gap-2"><ArrowRightLeft className="text-indigo-600"/>Nueva transferencia</h2><div className="grid md:grid-cols-2 gap-4"><select value={origin} onChange={e=>{setOrigin(Number(e.target.value));setItems([])}} className="border rounded-xl p-3"><option value={0}>Bodega de origen</option>{bodegas.map(b=><option key={b.idbodega} value={b.idbodega}>{b.nombre}</option>)}</select><select value={destination} onChange={e=>setDestination(Number(e.target.value))} className="border rounded-xl p-3"><option value={0}>Bodega de destino</option>{bodegas.filter(b=>b.idbodega!==origin).map(b=><option key={b.idbodega} value={b.idbodega}>{b.nombre}</option>)}</select></div>
   <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar producto para agregar..." className="border rounded-xl p-3 w-full"/>
   {query&&<div className="border rounded-xl max-h-48 overflow-auto">{products.map(p=><button type="button" key={p.idproducto} onClick={()=>add(p)} className="w-full flex justify-between p-3 hover:bg-slate-50 border-b text-left"><span>{p.nombre_producto}</span><span className="font-bold">Stock: {Number(p.stock)}</span></button>)}</div>}
   {items.map((it,i)=><div key={it.idproducto} className="flex items-center gap-3 bg-slate-50 p-3 rounded-xl"><span className="flex-1 font-semibold">{it.nombre_producto}</span><span className="text-xs text-slate-500">Disponible {it.stock}</span><input type="number" min="0.01" max={it.stock} step="0.01" value={it.cantidad} onChange={e=>setItems(v=>v.map((x,j)=>j===i?{...x,cantidad:Number(e.target.value)}:x))} className="w-28 border rounded-lg p-2"/><button onClick={()=>setItems(v=>v.filter((_,j)=>j!==i))} className="text-rose-500"><Ban/></button></div>)}
   <button disabled={!origin||!destination||!items.length} onClick={createTransfer} className="bg-indigo-600 disabled:bg-slate-300 text-white rounded-xl px-5 py-3 font-bold">Guardar transferencia pendiente</button>
  </section>
  <section className="bg-white border rounded-3xl overflow-hidden"><h2 className="text-xl font-black p-6">Historial de transferencias</h2><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left"><tr><th className="p-4">Número</th><th>Ruta</th><th>Productos</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{transfers.map(t=><tr key={t.idtransferencia} className="border-t"><td className="p-4 font-mono font-bold">{t.numero}</td><td>{t.bodega_origen} → {t.bodega_destino}</td><td>{t.productos} / {Number(t.unidades)} uds.</td><td><span className="font-bold">{t.estado.replace('_',' ')}</span></td><td className="space-x-2">{t.estado==='PENDIENTE'&&<><button onClick={()=>action(t.idtransferencia,'send')} className="p-2 text-indigo-600" title="Enviar"><Send/></button><button onClick={()=>action(t.idtransferencia,'cancel')} className="p-2 text-rose-500" title="Cancelar"><Ban/></button></>}{t.estado==='EN_TRANSITO'&&<button onClick={()=>action(t.idtransferencia,'receive')} className="p-2 text-emerald-600" title="Confirmar recepción"><PackageCheck/></button>}</td></tr>)}</tbody></table></div></section>
 </div>
}
